1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [1]:
import numpy as np

# Integer veri tipinde bir boyutlu array oluşturulması
array1 = np.array([3, 7, 9, 2, 1], dtype=int)

# Array bilgileri
print("Array:", array1)
print("Boyut:", array1.ndim)
print("Eleman sayısı:", array1.size)
print("Şekli:", array1.shape)



Array: [3 7 9 2 1]
Boyut: 1
Eleman sayısı: 5
Şekli: (5,)


2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]



In [2]:
# İki boyutlu array
array2d = np.array([[1, 2, 6, 7],
                    [4, 3, 9, 5]])

# Üç boyutlu array
array3d = np.array([[[7, 5, 14], [21, 8, 11]],
                    [[8, 6, 20], [14, 3, 9]]])

# İki boyutlu array bilgileri
print("2D Array:\n", array2d)
print("Boyut:", array2d.ndim)
print("Şekil (satır, sütun):", array2d.shape)
print("Eleman sayısı:", array2d.size)

# Üç boyutlu array bilgileri
print("3D Array:\n", array3d)
print("Boyut:", array3d.ndim)
print("Şekil:", array3d.shape)
print("Eleman sayısı:", array3d.size)


2D Array:
 [[1 2 6 7]
 [4 3 9 5]]
Boyut: 2
Şekil (satır, sütun): (2, 4)
Eleman sayısı: 8
3D Array:
 [[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyut: 3
Şekil: (2, 2, 3)
Eleman sayısı: 12


3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

İki boyutlu arraydaki 2 elemanına ulaşalım.

İki boyutlu arraydaki 7 elemanına ulaşalım.

Üç boyutlu arraydaki 9 elemanına ulaşalım.

Üç boyutlu arraydaki 5 elemanına ulaşalım.

In [3]:
# 2 elemanı
print("2D arraydeki 2 elemanı:", array2d[0, 1])

# 7 elemanı
print("2D arraydeki 7 elemanı:", array2d[0, 3])

# 9 elemanı
print("3D arraydeki 9 elemanı:", array3d[1, 1, 2])

# 5 elemanı
print("3D arraydeki 5 elemanı:", array3d[0, 0, 1])


2D arraydeki 2 elemanı: 2
2D arraydeki 7 elemanı: 7
3D arraydeki 9 elemanı: 9
3D arraydeki 5 elemanı: 5


4. Arrayler üzerinde slicing işlemi uygulayalım.

İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım

In [4]:
# 2 ve 6 elemanları
print("2D arraydeki 2 ve 6 elemanları:", array2d[0, 1:3])

# 3, 9, 5 elemanları
print("2D arraydeki 3, 9, 5 elemanları:", array2d[1, 1:])

# 21, 8, 11 elemanları
print("3D arraydeki 21, 8, 11 elemanları:", array3d[0, 1, :])

# 6, 20 elemanları
print("3D arraydeki 6, 20 elemanları:", array3d[1, 0, 1:3])


2D arraydeki 2 ve 6 elemanları: [2 6]
2D arraydeki 3, 9, 5 elemanları: [3 9 5]
3D arraydeki 21, 8, 11 elemanları: [21  8 11]
3D arraydeki 6, 20 elemanları: [ 6 20]


5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [5]:
# 5x3 sıfır ve birlerden oluşan arrayler
zeros_array = np.zeros((5, 3), dtype=int)
ones_array = np.ones((5, 3), dtype=int)

# Satır bazında birleştirme (dikey - alt alta)
concat_axis0 = np.concatenate((zeros_array, ones_array), axis=0)
print("Satır bazında birleştirme:\n", concat_axis0)

# Sütun bazında birleştirme (yatay - yan yana)
concat_axis1 = np.concatenate((zeros_array, ones_array), axis=1)
print("Sütun bazında birleştirme:\n", concat_axis1)


Satır bazında birleştirme:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Sütun bazında birleştirme:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
